export const PATHS = {
  login: () => `/login`,
  setNickName: (socialType: "kakao" | "google" | "apple") => `/setnickname/${socialType}`,
  home: () => `/`,
  goals: () => `/goals`,
  goalsMore: () => `/goals/more`,
  goalsEdit: () => `/goals/edit`,
  analysis: () => `/analysis`,
  retrospectCreate: () => `/retrospect/new`,
  retrospectRecommend: () => `/retrospect/recommend`,
  retrospectRecommendDone: () => `/retrospect/recommend/done`,
  write: () => `/write`,
  completeRetrospectCreate: () => `/retrospect/complete`,
  template: (spaceId: string) => `/space/${spaceId}/templates`,
  viewDetailTemplate: () => `/template`,
  spaceCreate: () => `/space/create`,
  spaceDetail: (spaceId: string) => `/space/${spaceId}`,
  myInfo: () => `/myinfo`,
  myInfoModify: () => `/myinfo/modify`,
  userDeletion: () => `/myinfo/userdeletion`,
  notices: () => `/myinfo/notices`,
  help: () => `/myinfo/help`,
  license: () => `/myinfo/license`,
  termsofservice: () => `/myinfo/termsofservice`,
  privacypolicy: () => `/myinfo/privacypolicy`,
  feedback: () => `/myinfo/feedback`,
  retrospectAnalysis: (spaceId: string, retrospectId: number) => `/retrospect/analysis?spaceId=${spaceId}&retrospectId=${retrospectId}`,
} as const;
